<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            'MK' => [
                ['mk' => 'Скопје', 'sr' => 'Скопље', 'hr' => 'Skoplje', 'sq' => 'Shkupi', 'en' => 'Skoplje'],
                ['mk' => 'Битола', 'sr' => 'Битољ', 'hr' => 'Bitola', 'sq' => 'Manastiri', 'en' => 'Bitola'],
                ['mk' => 'Куманово', 'sr' => 'Куманово', 'hr' => 'Kumanovo', 'sq' => 'Kumanova', 'en' => 'Kumanovo'],
                ['mk' => 'Прилеп', 'sr' => 'Прилеп', 'hr' => 'Prilep', 'sq' => 'Prilepi', 'en' => 'Prilep'],
                ['mk' => 'Тетово', 'sr' => 'Тетово', 'hr' => 'Tetovo', 'sq' => 'Tetova', 'en' => 'Tetovo'],
                ['mk' => 'Охрид', 'sr' => 'Охрид', 'hr' => 'Ohrid', 'sq' => 'Ohri', 'en' => 'Ohrid'],
                ['mk' => 'Велес', 'sr' => 'Велес', 'hr' => 'Veles', 'sq' => 'Velesi', 'en' => 'Veles'],
                ['mk' => 'Штип', 'sr' => 'Штип', 'hr' => 'Štip', 'sq' => 'Shtipi', 'en' => 'Štip'],
                ['mk' => 'Гостивар', 'sr' => 'Гостивар', 'hr' => 'Gostivar', 'sq' => 'Gostivari', 'en' => 'Gostivar'],
                ['mk' => 'Струмица', 'sr' => 'Струмица', 'hr' => 'Strumica', 'sq' => 'Strumica', 'en' => 'Strumica'],
                ['mk' => 'Кавадарци', 'sr' => 'Кавадарци', 'hr' => 'Kavadarci', 'sq' => 'Kavadarci', 'en' => 'Kavadarci'],
                ['mk' => 'Кочани', 'sr' => 'Кочани', 'hr' => 'Kočani', 'sq' => 'Koçani', 'en' => 'Kočani'],
                ['mk' => 'Кичево', 'sr' => 'Кичево', 'hr' => 'Kičevo', 'sq' => 'Kërçova', 'en' => 'Kičevo'],
                ['mk' => 'Струга', 'sr' => 'Струга', 'hr' => 'Struga', 'sq' => 'Struga', 'en' => 'Struga'],
                ['mk' => 'Радовиш', 'sr' => 'Радовиш', 'hr' => 'Radoviš', 'sq' => 'Radovishi', 'en' => 'Radoviš'],
                ['mk' => 'Гевгелија', 'sr' => 'Ђевђелија', 'hr' => 'Đevđelija', 'sq' => 'Gjevgjelia', 'en' => 'Đevđelija'],
                ['mk' => 'Дебар', 'sr' => 'Дебар', 'hr' => 'Debar', 'sq' => 'Dibra', 'en' => 'Debar'],
                ['mk' => 'Крива Паланка', 'sr' => 'Крива Паланка', 'hr' => 'Kriva Palanka', 'sq' => 'Kriva Pallanka', 'en' => 'Kriva Palanka'],
                ['mk' => 'Свети Николе', 'sr' => 'Свети Николе', 'hr' => 'Sveti Nikole', 'sq' => 'Shën Nikolla', 'en' => 'Sveti Nikole'],
                ['mk' => 'Неготино', 'sr' => 'Неготино', 'hr' => 'Negotino', 'sq' => 'Negotina', 'en' => 'Negotino'],
                ['mk' => 'Виница', 'sr' => 'Виница', 'hr' => 'Vinica', 'sq' => 'Vinica', 'en' => 'Vinica'],
                ['mk' => 'Кратово', 'sr' => 'Кратово', 'hr' => 'Kratovo', 'sq' => 'Kratova', 'en' => 'Kratovo'],
                ['mk' => 'Делчево', 'sr' => 'Делчево', 'hr' => 'Delčevo', 'sq' => 'Dellçeva', 'en' => 'Delčevo'],
                ['mk' => 'Пробиштип', 'sr' => 'Пробиштип', 'hr' => 'Probištip', 'sq' => 'Probishtipi', 'en' => 'Probištip'],
                ['mk' => 'Македонски Брод', 'sr' => 'Македонски Брод', 'hr' => 'Makedonski Brod', 'sq' => 'Brodi i Maqedonisë', 'en' => 'Makedonski Brod'],
                ['mk' => 'Демир Хисар', 'sr' => 'Демир Хисар', 'hr' => 'Demir Hisar', 'sq' => 'Demir Hisari', 'en' => 'Demir Hisar'],
                ['mk' => 'Крушево', 'sr' => 'Крушево', 'hr' => 'Kruševo', 'sq' => 'Krusheva', 'en' => 'Kruševo'],
                ['mk' => 'Ресен', 'sr' => 'Ресен', 'hr' => 'Resen', 'sq' => 'Resnja', 'en' => 'Resen'],
                ['mk' => 'Валандово', 'sr' => 'Валандово', 'hr' => 'Valandovo', 'sq' => 'Vallandova', 'en' => 'Valandovo'],
                ['mk' => 'Берово', 'sr' => 'Берово', 'hr' => 'Berovo', 'sq' => 'Berova', 'en' => 'Berovo'],
                ['mk' => 'Пехчево', 'sr' => 'Пехчево', 'hr' => 'Pehčevo', 'sq' => 'Pehçeva', 'en' => 'Pehčevo'],
                ['mk' => 'Македонска Каменица', 'sr' => 'Македонска Каменица', 'hr' => 'Makedonska Kamenica', 'sq' => 'Kamenica e Maqedonisë', 'en' => 'Makedonska Kamenica'],
                ['mk' => 'Богданци', 'sr' => 'Богданци', 'hr' => 'Bogdanci', 'sq' => 'Bogdanci', 'en' => 'Bogdanci'],
                ['mk' => 'Демир Капија', 'sr' => 'Демир Капија', 'hr' => 'Demir Kapija', 'sq' => 'Demir Kapia', 'en' => 'Demir Kapija'],
                ['mk' => 'Пласница', 'sr' => 'Пласница', 'hr' => 'Plasnica', 'sq' => 'Plasnica', 'en' => 'Plasnica'],
                ['mk' => 'Росоман', 'sr' => 'Росоман', 'hr' => 'Rosoman', 'sq' => 'Rosomani', 'en' => 'Rosoman'],
            ],
            'RS' => [
                ['mk' => 'Белград', 'sr' => 'Београд', 'hr' => 'Beograd', 'sq' => 'Beogradi', 'en' => 'Belgrade'],
                ['mk' => 'Нови Сад', 'sr' => 'Нови Сад', 'hr' => 'Novi Sad', 'sq' => 'Novi Sadi', 'en' => 'Novi Sad'],
                ['mk' => 'Ниш', 'sr' => 'Ниш', 'hr' => 'Niš', 'sq' => 'Nishi', 'en' => 'Niš'],
                ['mk' => 'Крагуевац', 'sr' => 'Крагујевац', 'hr' => 'Kragujevac', 'sq' => 'Kragujevci', 'en' => 'Kragujevac'],
                ['mk' => 'Суботица', 'sr' => 'Суботица', 'hr' => 'Subotica', 'sq' => 'Subotica', 'en' => 'Subotica'],
                ['mk' => 'Зрењанин', 'sr' => 'Зрењанин', 'hr' => 'Zrenjanin', 'sq' => 'Zrenjanini', 'en' => 'Zrenjanin'],
                ['mk' => 'Лесковац', 'sr' => 'Лесковац', 'hr' => 'Leskovac', 'sq' => 'Leskovac', 'en' => 'Leskovac'],
                ['mk' => 'Панчево', 'sr' => 'Панчево', 'hr' => 'Pančevo', 'sq' => 'Pančevo', 'en' => 'Pančevo'],
                ['mk' => 'Крушевац', 'sr' => 'Крушевац', 'hr' => 'Kruševac', 'sq' => 'Kruševac', 'en' => 'Kruševac'],
                ['mk' => 'Краљево', 'sr' => 'Краљево', 'hr' => 'Kraljevo', 'sq' => 'Kraljevo', 'en' => 'Kraljevo'],
                ['mk' => 'Нови Пазар', 'sr' => 'Нови Пазар', 'hr' => 'Novi Pazar', 'sq' => 'Novi Pazar', 'en' => 'Novi Pazar'],
                ['mk' => 'Чачак', 'sr' => 'Чачак', 'hr' => 'Čačak', 'sq' => 'Čačak', 'en' => 'Čačak'],
                ['mk' => 'Шабац', 'sr' => 'Шабац', 'hr' => 'Šabac', 'sq' => 'Šabac', 'en' => 'Šabac'],
                ['mk' => 'Смедерево', 'sr' => 'Смедерево', 'hr' => 'Smederevo', 'sq' => 'Smederevo', 'en' => 'Smederevo'],
                ['mk' => 'Ваљево', 'sr' => 'Ваљево', 'hr' => 'Valjevo', 'sq' => 'Valjevo', 'en' => 'Valjevo'],
                ['mk' => 'Врање', 'sr' => 'Врање', 'hr' => 'Vranje', 'sq' => 'Vranje', 'en' => 'Vranje'],
                ['mk' => 'Сремска Митровица', 'sr' => 'Сремска Митровица', 'hr' => 'Sremska Mitrovica', 'sq' => 'Sremska Mitrovica', 'en' => 'Sremska Mitrovica'],
                ['mk' => 'Лозница', 'sr' => 'Лозница', 'hr' => 'Loznica', 'sq' => 'Loznica', 'en' => 'Loznica'],
                ['mk' => 'Сомбор', 'sr' => 'Сомбор', 'hr' => 'Sombor', 'sq' => 'Sombor', 'en' => 'Sombor'],
                ['mk' => 'Ужице', 'sr' => 'Ужице', 'hr' => 'Užice', 'sq' => 'Užice', 'en' => 'Užice'],
                ['mk' => 'Пожаревац', 'sr' => 'Пожаревац', 'hr' => 'Požarevac', 'sq' => 'Požarevac', 'en' => 'Požarevac'],
                ['mk' => 'Јагодина', 'sr' => 'Јагодина', 'hr' => 'Jagodina', 'sq' => 'Jagodina', 'en' => 'Jagodina'],
                ['mk' => 'Стара Пазова', 'sr' => 'Стара Пазова', 'hr' => 'Stara Pazova', 'sq' => 'Stara Pazova', 'en' => 'Stara Pazova'],
                ['mk' => 'Пирот', 'sr' => 'Пирот', 'hr' => 'Pirot', 'sq' => 'Pirot', 'en' => 'Pirot'],
                ['mk' => 'Кикинда', 'sr' => 'Кикинда', 'hr' => 'Kikinda', 'sq' => 'Kikinda', 'en' => 'Kikinda'],
                ['mk' => 'Рума', 'sr' => 'Рума', 'hr' => 'Ruma', 'sq' => 'Ruma', 'en' => 'Ruma'],
                ['mk' => 'Бачка Паланка', 'sr' => 'Бачка Паланка', 'hr' => 'Bačka Palanka', 'sq' => 'Bačka Palanka', 'en' => 'Bačka Palanka'],
                ['mk' => 'Зајечар', 'sr' => 'Зајечар', 'hr' => 'Zaječar', 'sq' => 'Zaječar', 'en' => 'Zaječar'],
                ['mk' => 'Параќин', 'sr' => 'Параћин', 'hr' => 'Paraćin', 'sq' => 'Paraćin', 'en' => 'Paraćin'],
                ['mk' => 'Вршац', 'sr' => 'Вршац', 'hr' => 'Vršac', 'sq' => 'Vršac', 'en' => 'Vršac'],
                ['mk' => 'Инѓија', 'sr' => 'Инђија', 'hr' => 'Inđija', 'sq' => 'Inđija', 'en' => 'Inđija'],
                ['mk' => 'Алексинац', 'sr' => 'Алексинац', 'hr' => 'Aleksinac', 'sq' => 'Aleksinac', 'en' => 'Aleksinac'],
                ['mk' => 'Смедеревска Паланка', 'sr' => 'Смедеревска Паланка', 'hr' => 'Smederevska Palanka', 'sq' => 'Smederevska Palanka', 'en' => 'Smederevska Palanka'],
                ['mk' => 'Аранѓеловац', 'sr' => 'Аранђеловац', 'hr' => 'Aranđelovac', 'sq' => 'Aranđelovac', 'en' => 'Aranđelovac'],
                ['mk' => 'Бујановац', 'sr' => 'Бујановац', 'hr' => 'Bujanovac', 'sq' => 'Bujanovac', 'en' => 'Bujanovac'],
                ['mk' => 'Бор', 'sr' => 'Бор', 'hr' => 'Bor', 'sq' => 'Bor', 'en' => 'Bor'],
                ['mk' => 'Горњи Милановац', 'sr' => 'Горњи Милановац', 'hr' => 'Gornji Milanovac', 'sq' => 'Gornji Milanovac', 'en' => 'Gornji Milanovac'],
                ['mk' => 'Прокупље', 'sr' => 'Прокупље', 'hr' => 'Prokuplje', 'sq' => 'Prokuplje', 'en' => 'Prokuplje'],
                ['mk' => 'Врбас', 'sr' => 'Врбас', 'hr' => 'Vrbas', 'sq' => 'Vrbas', 'en' => 'Vrbas'],
                ['mk' => 'Трстеник', 'sr' => 'Трстеник', 'hr' => 'Trstenik', 'sq' => 'Trstenik', 'en' => 'Trstenik'],
                ['mk' => 'Кула', 'sr' => 'Кула', 'hr' => 'Kula', 'sq' => 'Kula', 'en' => 'Kula'],
                ['mk' => 'Велика Плана', 'sr' => 'Велика Плана', 'hr' => 'Velika Plana', 'sq' => 'Velika Plana', 'en' => 'Velika Plana'],
                ['mk' => 'Прешево', 'sr' => 'Прешево', 'hr' => 'Preševo', 'sq' => 'Preševo', 'en' => 'Preševo'],
                ['mk' => 'Тутин', 'sr' => 'Тутин', 'hr' => 'Tutin', 'sq' => 'Tutin', 'en' => 'Tutin'],
                ['mk' => 'Пријепоље', 'sr' => 'Пријепоље', 'hr' => 'Prijepolje', 'sq' => 'Prijepolje', 'en' => 'Prijepolje'],
                ['mk' => 'Бечеј', 'sr' => 'Бечеј', 'hr' => 'Bečej', 'sq' => 'Bečej', 'en' => 'Bečej'],
                ['mk' => 'Неготин', 'sr' => 'Неготин', 'hr' => 'Negotin', 'sq' => 'Negotin', 'en' => 'Negotin'],
                ['mk' => 'Ковин', 'sr' => 'Ковин', 'hr' => 'Kovin', 'sq' => 'Kovin', 'en' => 'Kovin'],
                ['mk' => 'Шид', 'sr' => 'Шид', 'hr' => 'Šid', 'sq' => 'Šid', 'en' => 'Šid'],
                ['mk' => 'Ивањица', 'sr' => 'Ивањица', 'hr' => 'Ivanjica', 'sq' => 'Ivanjica', 'en' => 'Ivanjica'],
                ['mk' => 'Бачка Топола', 'sr' => 'Бачка Топола', 'hr' => 'Bačka Topola', 'sq' => 'Bačka Topola', 'en' => 'Bačka Topola'],
                ['mk' => 'Пожега', 'sr' => 'Пожега', 'hr' => 'Požega', 'sq' => 'Požega', 'en' => 'Požega'],
                ['mk' => 'Петровац на Млави', 'sr' => 'Петровац на Млави', 'hr' => 'Petrovac na Mlavi', 'sq' => 'Petrovac na Mlavi', 'en' => 'Petrovac na Mlavi'],
                ['mk' => 'Темерин', 'sr' => 'Темерин', 'hr' => 'Temerin', 'sq' => 'Temerin', 'en' => 'Temerin'],
                ['mk' => 'Уб', 'sr' => 'Уб', 'hr' => 'Ub', 'sq' => 'Ub', 'en' => 'Ub'],
                ['mk' => 'Власотинце', 'sr' => 'Власотинце', 'hr' => 'Vlasotince', 'sq' => 'Vlasotince', 'en' => 'Vlasotince'],
                ['mk' => 'Књажевац', 'sr' => 'Књажевац', 'hr' => 'Knjaževac', 'sq' => 'Knjaževac', 'en' => 'Knjaževac'],
                ['mk' => 'Ќуприја', 'sr' => 'Ћуприја', 'hr' => 'Ćuprija', 'sq' => 'Ćuprija', 'en' => 'Ćuprija'],
                ['mk' => 'Врњачка Бања', 'sr' => 'Врњачка Бања', 'hr' => 'Vrnjačka Banja', 'sq' => 'Vrnjačka Banja', 'en' => 'Vrnjačka Banja'],
                ['mk' => 'Оџаци', 'sr' => 'Оџаци', 'hr' => 'Odžaci', 'sq' => 'Odžaci', 'en' => 'Odžaci'],
                ['mk' => 'Богатиќ', 'sr' => 'Богатић', 'hr' => 'Bogatić', 'sq' => 'Bogatić', 'en' => 'Bogatić'],
                ['mk' => 'Сјеница', 'sr' => 'Сјеница', 'hr' => 'Sjenica', 'sq' => 'Sjenica', 'en' => 'Sjenica'],
                ['mk' => 'Жабаљ', 'sr' => 'Жабаљ', 'hr' => 'Žabalj', 'sq' => 'Žabalj', 'en' => 'Žabalj'],
                ['mk' => 'Бајина Башта', 'sr' => 'Бајина Башта', 'hr' => 'Bajina Bašta', 'sq' => 'Bajina Bašta', 'en' => 'Bajina Bašta'],
                ['mk' => 'Прибој', 'sr' => 'Прибој', 'hr' => 'Priboj', 'sq' => 'Priboj', 'en' => 'Priboj'],
                ['mk' => 'Апатин', 'sr' => 'Апатин', 'hr' => 'Apatin', 'sq' => 'Apatin', 'en' => 'Apatin'],
                ['mk' => 'Александровац', 'sr' => 'Александровац', 'hr' => 'Aleksandrovac', 'sq' => 'Aleksandrovac', 'en' => 'Aleksandrovac'],
                ['mk' => 'Рашка', 'sr' => 'Рашка', 'hr' => 'Raška', 'sq' => 'Raška', 'en' => 'Raška'],
                ['mk' => 'Ковачица', 'sr' => 'Ковачица', 'hr' => 'Kovačica', 'sq' => 'Kovačica', 'en' => 'Kovačica'],
                ['mk' => 'Кањижа', 'sr' => 'Кањижа', 'hr' => 'Kanjiža', 'sq' => 'Kanjiža', 'en' => 'Kanjiža'],
                ['mk' => 'Свилајнац', 'sr' => 'Свилајнац', 'hr' => 'Svilajnac', 'sq' => 'Svilajnac', 'en' => 'Svilajnac'],
                ['mk' => 'Нови Бечеј', 'sr' => 'Нови Бечеј', 'hr' => 'Novi Bečej', 'sq' => 'Novi Bečej', 'en' => 'Novi Bečej'],
                ['mk' => 'Топола', 'sr' => 'Топола', 'hr' => 'Topola', 'sq' => 'Topola', 'en' => 'Topola'],
                ['mk' => 'Пеќинци', 'sr' => 'Пећинци', 'hr' => 'Pećinci', 'sq' => 'Pećinci', 'en' => 'Pećinci'],
                ['mk' => 'Деспотовац', 'sr' => 'Деспотовац', 'hr' => 'Despotovac', 'sq' => 'Despotovac', 'en' => 'Despotovac'],
                ['mk' => 'Лебане', 'sr' => 'Лебане', 'hr' => 'Lebane', 'sq' => 'Lebane', 'en' => 'Lebane'],
                ['mk' => 'Сента', 'sr' => 'Сента', 'hr' => 'Senta', 'sq' => 'Senta', 'en' => 'Senta'],
                ['mk' => 'Владичин Хан', 'sr' => 'Владичин Хан', 'hr' => 'Vladičin Han', 'sq' => 'Vladičin Han', 'en' => 'Vladičin Han'],
                ['mk' => 'Кладово', 'sr' => 'Кладово', 'hr' => 'Kladovo', 'sq' => 'Kladovo', 'en' => 'Kladovo'],
                ['mk' => 'Алибунар', 'sr' => 'Алибунар', 'hr' => 'Alibunar', 'sq' => 'Alibunar', 'en' => 'Alibunar'],
                ['mk' => 'Ариље', 'sr' => 'Ариље', 'hr' => 'Arilje', 'sq' => 'Arilje', 'en' => 'Arilje'],
                ['mk' => 'Сурдулица', 'sr' => 'Сурдулица', 'hr' => 'Surdulica', 'sq' => 'Surdulica', 'en' => 'Surdulica'],
                ['mk' => 'Лучани', 'sr' => 'Лучани', 'hr' => 'Lučani', 'sq' => 'Lučani', 'en' => 'Lučani'],
                ['mk' => 'Дољевац', 'sr' => 'Дољевац', 'hr' => 'Doljevac', 'sq' => 'Doljevac', 'en' => 'Doljevac'],
                ['mk' => 'Куршумлија', 'sr' => 'Куршумлија', 'hr' => 'Kuršumlija', 'sq' => 'Kuršumlija', 'en' => 'Kuršumlija'],
                ['mk' => 'Велико Градиште', 'sr' => 'Велико Градиште', 'hr' => 'Veliko Gradište', 'sq' => 'Veliko Gradište', 'en' => 'Veliko Gradište'],
                ['mk' => 'Чајетина', 'sr' => 'Чајетина', 'hr' => 'Čajetina', 'sq' => 'Čajetina', 'en' => 'Čajetina'],
                ['mk' => 'Мајданпек', 'sr' => 'Мајданпек', 'hr' => 'Majdanpek', 'sq' => 'Majdanpek', 'en' => 'Majdanpek'],
                ['mk' => 'Бела Црква', 'sr' => 'Бела Црква', 'hr' => 'Bela Crkva', 'sq' => 'Bela Crkva', 'en' => 'Bela Crkva'],
                ['mk' => 'Владимирци', 'sr' => 'Владимирци', 'hr' => 'Vladimirci', 'sq' => 'Vladimirci', 'en' => 'Vladimirci'],
                ['mk' => 'Крупањ', 'sr' => 'Крупањ', 'hr' => 'Krupanj', 'sq' => 'Krupanj', 'en' => 'Krupanj'],
                ['mk' => 'Србобран', 'sr' => 'Србобран', 'hr' => 'Srbobran', 'sq' => 'Srbobran', 'en' => 'Srbobran'],
                ['mk' => 'Варварин', 'sr' => 'Варварин', 'hr' => 'Varvarin', 'sq' => 'Varvarin', 'en' => 'Varvarin'],
                ['mk' => 'Тител', 'sr' => 'Тител', 'hr' => 'Titel', 'sq' => 'Titel', 'en' => 'Titel'],
                ['mk' => 'Беочин', 'sr' => 'Беочин', 'hr' => 'Beočin', 'sq' => 'Beočin', 'en' => 'Beočin'],
                ['mk' => 'Лајковац', 'sr' => 'Лајковац', 'hr' => 'Lajkovac', 'sq' => 'Lajkovac', 'en' => 'Lajkovac'],
                ['mk' => 'Житораѓа', 'sr' => 'Житорађа', 'hr' => 'Žitorađa', 'sq' => 'Žitorađa', 'en' => 'Žitorađa'],
                ['mk' => 'Брус', 'sr' => 'Брус', 'hr' => 'Brus', 'sq' => 'Brus', 'en' => 'Brus'],
                ['mk' => 'Нова Варош', 'sr' => 'Нова Варош', 'hr' => 'Nova Varoš', 'sq' => 'Nova Varoš', 'en' => 'Nova Varoš'],
                ['mk' => 'Житиште', 'sr' => 'Житиште', 'hr' => 'Žitište', 'sq' => 'Žitište', 'en' => 'Žitište'],
                ['mk' => 'Ада', 'sr' => 'Ада', 'hr' => 'Ada', 'sq' => 'Ada', 'en' => 'Ada'],
                ['mk' => 'Сокобања', 'sr' => 'Сокобања', 'hr' => 'Sokobanja', 'sq' => 'Sokobanja', 'en' => 'Sokobanja'],
                ['mk' => 'Љубовија', 'sr' => 'Љубовија', 'hr' => 'Ljubovija', 'sq' => 'Ljubovija', 'en' => 'Ljubovija'],
                ['mk' => 'Мионица', 'sr' => 'Мионица', 'hr' => 'Mionica', 'sq' => 'Mionica', 'en' => 'Mionica'],
                ['mk' => 'Мерошина', 'sr' => 'Мерошина', 'hr' => 'Merošina', 'sq' => 'Merošina', 'en' => 'Merošina'],
                ['mk' => 'Кучево', 'sr' => 'Кучево', 'hr' => 'Kučevo', 'sq' => 'Kučevo', 'en' => 'Kučevo'],
                ['mk' => 'Книќ', 'sr' => 'Кнић', 'hr' => 'Knić', 'sq' => 'Knić', 'en' => 'Knić'],
                ['mk' => 'Бачки Петровац', 'sr' => 'Бачки Петровац', 'hr' => 'Bački Petrovac', 'sq' => 'Bački Petrovac', 'en' => 'Bački Petrovac'],
                ['mk' => 'Бач', 'sr' => 'Бач', 'hr' => 'Bač', 'sq' => 'Bač', 'en' => 'Bač'],
                ['mk' => 'Мали Зворник', 'sr' => 'Мали Зворник', 'hr' => 'Mali Zvornik', 'sq' => 'Mali Zvornik', 'en' => 'Mali Zvornik'],
                ['mk' => 'Коцељева', 'sr' => 'Коцељева', 'hr' => 'Koceljeva', 'sq' => 'Koceljeva', 'en' => 'Koceljeva'],
                ['mk' => 'Сврљиг', 'sr' => 'Сврљиг', 'hr' => 'Svrljig', 'sq' => 'Svrljig', 'en' => 'Svrljig'],
                ['mk' => 'Љиг', 'sr' => 'Љиг', 'hr' => 'Ljig', 'sq' => 'Ljig', 'en' => 'Ljig'],
                ['mk' => 'Сечањ', 'sr' => 'Сечањ', 'hr' => 'Sečanj', 'sq' => 'Sečanj', 'en' => 'Sečanj'],
                ['mk' => 'Бољевац', 'sr' => 'Бољевац', 'hr' => 'Boljevac', 'sq' => 'Boljevac', 'en' => 'Boljevac'],
                ['mk' => 'Косјериќ', 'sr' => 'Косјерић', 'hr' => 'Kosjerić', 'sq' => 'Kosjerić', 'en' => 'Kosjerić'],
                ['mk' => 'Баточина', 'sr' => 'Баточина', 'hr' => 'Batočina', 'sq' => 'Batočina', 'en' => 'Batočina'],
                ['mk' => 'Мали Иѓош', 'sr' => 'Мали Иђош', 'hr' => 'Mali Iđoš', 'sq' => 'Mali Iđoš', 'en' => 'Mali Iđoš'],
                ['mk' => 'Осечина', 'sr' => 'Осечина', 'hr' => 'Osečina', 'sq' => 'Osečina', 'en' => 'Osečina'],
                ['mk' => 'Бела Паланка', 'sr' => 'Бела Паланка', 'hr' => 'Bela Palanka', 'sq' => 'Bela Palanka', 'en' => 'Bela Palanka'],
            ],
            'HR' => [
                ['mk' => 'Загреб', 'sr' => 'Загреб', 'hr' => 'Zagreb', 'sq' => 'Zagrebi', 'en' => 'Zagreb'],
                ['mk' => 'Сплит', 'sr' => 'Сплит', 'hr' => 'Split', 'sq' => 'Spliti', 'en' => 'Split'],
                ['mk' => 'Риека', 'sr' => 'Ријека', 'hr' => 'Rijeka', 'sq' => 'Rijeka', 'en' => 'Rijeka'],
                ['mk' => 'Осиек', 'sr' => 'Осијек', 'hr' => 'Osijek', 'sq' => 'Osijeku', 'en' => 'Osijek'],
                ['mk' => 'Задар', 'sr' => 'Задар', 'hr' => 'Zadar', 'sq' => 'Zadari', 'en' => 'Zadar'],
                ['mk' => 'Дубровник', 'sr' => 'Дубровник', 'hr' => 'Dubrovnik', 'sq' => 'Dubrovniku', 'en' => 'Dubrovnik'],
                ['mk' => 'Велика Горица', 'sr' => 'Велика Горица', 'hr' => 'Velika Gorica', 'sq' => 'Velika Gorica', 'en' => 'Velika Gorica'],
                ['mk' => 'Пула', 'sr' => 'Пула', 'hr' => 'Pula', 'sq' => 'Pula', 'en' => 'Pula'],
                ['mk' => 'Славонски Брод', 'sr' => 'Славонски Брод', 'hr' => 'Slavonski Brod', 'sq' => 'Slavonski Brod', 'en' => 'Slavonski Brod'],
                ['mk' => 'Карловац', 'sr' => 'Карловац', 'hr' => 'Karlovac', 'sq' => 'Karlovac', 'en' => 'Karlovac'],
                ['mk' => 'Вараждин', 'sr' => 'Вараждин', 'hr' => 'Varaždin', 'sq' => 'Varaždin', 'en' => 'Varaždin'],
                ['mk' => 'Шибеник', 'sr' => 'Шибеник', 'hr' => 'Šibenik', 'sq' => 'Šibenik', 'en' => 'Šibenik'],
                ['mk' => 'Сисак', 'sr' => 'Сисак', 'hr' => 'Sisak', 'sq' => 'Sisak', 'en' => 'Sisak'],
                ['mk' => 'Каштела', 'sr' => 'Каштела', 'hr' => 'Kaštela', 'sq' => 'Kaštela', 'en' => 'Kaštela'],
                ['mk' => 'Самобор', 'sr' => 'Самобор', 'hr' => 'Samobor', 'sq' => 'Samobor', 'en' => 'Samobor'],
                ['mk' => 'Бјеловар', 'sr' => 'Бјеловар', 'hr' => 'Bjelovar', 'sq' => 'Bjelovar', 'en' => 'Bjelovar'],
                ['mk' => 'Винковци', 'sr' => 'Винковци', 'hr' => 'Vinkovci', 'sq' => 'Vinkovci', 'en' => 'Vinkovci'],
                ['mk' => 'Копривница', 'sr' => 'Копривница', 'hr' => 'Koprivnica', 'sq' => 'Koprivnica', 'en' => 'Koprivnica'],
                ['mk' => 'Чаковец', 'sr' => 'Чаковец', 'hr' => 'Čakovec', 'sq' => 'Čakovec', 'en' => 'Čakovec'],
                ['mk' => 'Солин', 'sr' => 'Солин', 'hr' => 'Solin', 'sq' => 'Solin', 'en' => 'Solin'],
                ['mk' => 'Запрешиќ', 'sr' => 'Запрешић', 'hr' => 'Zaprešić', 'sq' => 'Zaprešić', 'en' => 'Zaprešić'],
                ['mk' => 'Ѓаково', 'sr' => 'Ђаково', 'hr' => 'Đakovo', 'sq' => 'Đakovo', 'en' => 'Đakovo'],
                ['mk' => 'Сињ', 'sr' => 'Сињ', 'hr' => 'Sinj', 'sq' => 'Sinj', 'en' => 'Sinj'],
                ['mk' => 'Вуковар', 'sr' => 'Вуковар', 'hr' => 'Vukovar', 'sq' => 'Vukovar', 'en' => 'Vukovar'],
                ['mk' => 'Пожега', 'sr' => 'Пожега', 'hr' => 'Požega', 'sq' => 'Požega', 'en' => 'Požega'],
                ['mk' => 'Петриња', 'sr' => 'Петриња', 'hr' => 'Petrinja', 'sq' => 'Petrinja', 'en' => 'Petrinja'],
                ['mk' => 'Кутина', 'sr' => 'Кутина', 'hr' => 'Kutina', 'sq' => 'Kutina', 'en' => 'Kutina'],
                ['mk' => 'Вировитица', 'sr' => 'Вировитица', 'hr' => 'Virovitica', 'sq' => 'Virovitica', 'en' => 'Virovitica'],
                ['mk' => 'Крижевци', 'sr' => 'Крижевци', 'hr' => 'Križevci', 'sq' => 'Križevci', 'en' => 'Križevci'],
                ['mk' => 'Света Недеља', 'sr' => 'Света Недеља', 'hr' => 'Sveta Nedelja', 'sq' => 'Sveta Nedelja', 'en' => 'Sveta Nedelja'],
                ['mk' => 'Дуго Село', 'sr' => 'Дуго Село', 'hr' => 'Dugo Selo', 'sq' => 'Dugo Selo', 'en' => 'Dugo Selo'],
                ['mk' => 'Пореч', 'sr' => 'Пореч', 'hr' => 'Poreč', 'sq' => 'Poreč', 'en' => 'Poreč'],
                ['mk' => 'Метковиќ', 'sr' => 'Метковић', 'hr' => 'Metković', 'sq' => 'Metković', 'en' => 'Metković'],
                ['mk' => 'Свети Иван Зелина', 'sr' => 'Свети Иван Зелина', 'hr' => 'Sveti Ivan Zelina', 'sq' => 'Sveti Ivan Zelina', 'en' => 'Sveti Ivan Zelina'],
                ['mk' => 'Јастребарско', 'sr' => 'Јастребарско', 'hr' => 'Jastrebarsko', 'sq' => 'Jastrebarsko', 'en' => 'Jastrebarsko'],
                ['mk' => 'Нашице', 'sr' => 'Нашице', 'hr' => 'Našice', 'sq' => 'Našice', 'en' => 'Našice'],
                ['mk' => 'Омиш', 'sr' => 'Омиш', 'hr' => 'Omiš', 'sq' => 'Omiš', 'en' => 'Omiš'],
                ['mk' => 'Макарска', 'sr' => 'Макарска', 'hr' => 'Makarska', 'sq' => 'Makarska', 'en' => 'Makarska'],
                ['mk' => 'Иваниќ-Град', 'sr' => 'Иванић-Град', 'hr' => 'Ivanić-Grad', 'sq' => 'Ivanić-Grad', 'en' => 'Ivanić-Grad'],
                ['mk' => 'Врбовец', 'sr' => 'Врбовец', 'hr' => 'Vrbovec', 'sq' => 'Vrbovec', 'en' => 'Vrbovec'],
                ['mk' => 'Ровињ', 'sr' => 'Ровињ', 'hr' => 'Rovinj', 'sq' => 'Rovinj', 'en' => 'Rovinj'],
                ['mk' => 'Иванец', 'sr' => 'Иванец', 'hr' => 'Ivanec', 'sq' => 'Ivanec', 'en' => 'Ivanec'],
                ['mk' => 'Умаг', 'sr' => 'Умаг', 'hr' => 'Umag', 'sq' => 'Umag', 'en' => 'Umag'],
                ['mk' => 'Трогир', 'sr' => 'Трогир', 'hr' => 'Trogir', 'sq' => 'Trogir', 'en' => 'Trogir'],
                ['mk' => 'Огулин', 'sr' => 'Огулин', 'hr' => 'Ogulin', 'sq' => 'Ogulin', 'en' => 'Ogulin'],
                ['mk' => 'Нови Мароф', 'sr' => 'Нови Мароф', 'hr' => 'Novi Marof', 'sq' => 'Novi Marof', 'en' => 'Novi Marof'],
                ['mk' => 'Нова Градишка', 'sr' => 'Нова Градишка', 'hr' => 'Nova Gradiška', 'sq' => 'Nova Gradiška', 'en' => 'Nova Gradiška'],
                ['mk' => 'Книн', 'sr' => 'Книн', 'hr' => 'Knin', 'sq' => 'Knin', 'en' => 'Knin'],
                ['mk' => 'Крапина', 'sr' => 'Крапина', 'hr' => 'Krapina', 'sq' => 'Krapina', 'en' => 'Krapina'],
                ['mk' => 'Слатина', 'sr' => 'Слатина', 'hr' => 'Slatina', 'sq' => 'Slatina', 'en' => 'Slatina'],
                ['mk' => 'Госпиќ', 'sr' => 'Госпић', 'hr' => 'Gospić', 'sq' => 'Gospić', 'en' => 'Gospić'],
                ['mk' => 'Новска', 'sr' => 'Новска', 'hr' => 'Novska', 'sq' => 'Novska', 'en' => 'Novska'],
                ['mk' => 'Опатија', 'sr' => 'Опатија', 'hr' => 'Opatija', 'sq' => 'Opatija', 'en' => 'Opatija'],
                ['mk' => 'Лабин', 'sr' => 'Лабин', 'hr' => 'Labin', 'sq' => 'Labin', 'en' => 'Labin'],
                ['mk' => 'Поповача', 'sr' => 'Поповача', 'hr' => 'Popovača', 'sq' => 'Popovača', 'en' => 'Popovača'],
                ['mk' => 'Дуга Реса', 'sr' => 'Дуга Реса', 'hr' => 'Duga Resa', 'sq' => 'Duga Resa', 'en' => 'Duga Resa'],
                ['mk' => 'Кастав', 'sr' => 'Кастав', 'hr' => 'Kastav', 'sq' => 'Kastav', 'en' => 'Kastav'],
                ['mk' => 'Дарувар', 'sr' => 'Дарувар', 'hr' => 'Daruvar', 'sq' => 'Daruvar', 'en' => 'Daruvar'],
                ['mk' => 'Цриквеница', 'sr' => 'Цриквеница', 'hr' => 'Crikvenica', 'sq' => 'Crikvenica', 'en' => 'Crikvenica'],
                ['mk' => 'Валпово', 'sr' => 'Валпово', 'hr' => 'Valpovo', 'sq' => 'Valpovo', 'en' => 'Valpovo'],
                ['mk' => 'Бенковац', 'sr' => 'Бенковац', 'hr' => 'Benkovac', 'sq' => 'Benkovac', 'en' => 'Benkovac'],
                ['mk' => 'Имотски', 'sr' => 'Имотски', 'hr' => 'Imotski', 'sq' => 'Imotski', 'en' => 'Imotski'],
                ['mk' => 'Жупања', 'sr' => 'Жупања', 'hr' => 'Županja', 'sq' => 'Županja', 'en' => 'Županja'],
                ['mk' => 'Плетерница', 'sr' => 'Плетерница', 'hr' => 'Pleternica', 'sq' => 'Pleternica', 'en' => 'Pleternica'],
                ['mk' => 'Белишќе', 'sr' => 'Белишће', 'hr' => 'Belišće', 'sq' => 'Belišće', 'en' => 'Belišće'],
                ['mk' => 'Забок', 'sr' => 'Забок', 'hr' => 'Zabok', 'sq' => 'Zabok', 'en' => 'Zabok'],
                ['mk' => 'Водице', 'sr' => 'Водице', 'hr' => 'Vodice', 'sq' => 'Vodice', 'en' => 'Vodice'],
                ['mk' => 'Гарешница', 'sr' => 'Гарешница', 'hr' => 'Garešnica', 'sq' => 'Garešnica', 'en' => 'Garešnica'],
                ['mk' => 'Лудбрег', 'sr' => 'Лудбрег', 'hr' => 'Ludbreg', 'sq' => 'Ludbreg', 'en' => 'Ludbreg'],
                ['mk' => 'Оточац', 'sr' => 'Оточац', 'hr' => 'Otočac', 'sq' => 'Otočac', 'en' => 'Otočac'],
                ['mk' => 'Пазин', 'sr' => 'Пазин', 'hr' => 'Pazin', 'sq' => 'Pazin', 'en' => 'Pazin'],
                ['mk' => 'Плоче', 'sr' => 'Плоче', 'hr' => 'Ploče', 'sq' => 'Ploče', 'en' => 'Ploče'],
                ['mk' => 'Триљ', 'sr' => 'Триљ', 'hr' => 'Trilj', 'sq' => 'Trilj', 'en' => 'Trilj'],
                ['mk' => 'Доњи Михољац', 'sr' => 'Доњи Михољац', 'hr' => 'Donji Miholjac', 'sq' => 'Donji Miholjac', 'en' => 'Donji Miholjac'],
                ['mk' => 'Бели Манастир', 'sr' => 'Бели Манастир', 'hr' => 'Beli Manastir', 'sq' => 'Beli Manastir', 'en' => 'Beli Manastir'],
                ['mk' => 'Бакар', 'sr' => 'Бакар', 'hr' => 'Bakar', 'sq' => 'Bakar', 'en' => 'Bakar'],
                ['mk' => 'Мали Лошињ', 'sr' => 'Мали Лошињ', 'hr' => 'Mali Lošinj', 'sq' => 'Mali Lošinj', 'en' => 'Mali Lošinj'],
                ['mk' => 'Ѓурѓевац', 'sr' => 'Ђурђевац', 'hr' => 'Đurđevac', 'sq' => 'Đurđevac', 'en' => 'Đurđevac'],
                ['mk' => 'Раб', 'sr' => 'Раб', 'hr' => 'Rab', 'sq' => 'Rab', 'en' => 'Rab'],
                ['mk' => 'Глина', 'sr' => 'Глина', 'hr' => 'Glina', 'sq' => 'Glina', 'en' => 'Glina'],
                ['mk' => 'Пакрац', 'sr' => 'Пакрац', 'hr' => 'Pakrac', 'sq' => 'Pakrac', 'en' => 'Pakrac'],
                ['mk' => 'Прелог', 'sr' => 'Прелог', 'hr' => 'Prelog', 'sq' => 'Prelog', 'en' => 'Prelog'],
                ['mk' => 'Лепоглава', 'sr' => 'Лепоглава', 'hr' => 'Lepoglava', 'sq' => 'Lepoglava', 'en' => 'Lepoglava'],
                ['mk' => 'Чазма', 'sr' => 'Чазма', 'hr' => 'Čazma', 'sq' => 'Čazma', 'en' => 'Čazma'],
                ['mk' => 'Крк', 'sr' => 'Крк', 'hr' => 'Krk', 'sq' => 'Krk', 'en' => 'Krk'],
                ['mk' => 'Дрниш', 'sr' => 'Дрниш', 'hr' => 'Drniš', 'sq' => 'Drniš', 'en' => 'Drniš'],
                ['mk' => 'Бузет', 'sr' => 'Бузет', 'hr' => 'Buzet', 'sq' => 'Buzet', 'en' => 'Buzet'],
                ['mk' => 'Сењ', 'sr' => 'Сењ', 'hr' => 'Senj', 'sq' => 'Senj', 'en' => 'Senj'],
                ['mk' => 'Преграда', 'sr' => 'Преграда', 'hr' => 'Pregrada', 'sq' => 'Pregrada', 'en' => 'Pregrada'],
                ['mk' => 'Мурско Средишќе', 'sr' => 'Мурско Средишће', 'hr' => 'Mursko Središće', 'sq' => 'Mursko Središće', 'en' => 'Mursko Središće'],
                ['mk' => 'Водњан', 'sr' => 'Водњан', 'hr' => 'Vodnjan', 'sq' => 'Vodnjan', 'en' => 'Vodnjan'],
                ['mk' => 'Озаљ', 'sr' => 'Озаљ', 'hr' => 'Ozalj', 'sq' => 'Ozalj', 'en' => 'Ozalj'],
                ['mk' => 'Орославје', 'sr' => 'Орославје', 'hr' => 'Oroslavje', 'sq' => 'Oroslavje', 'en' => 'Oroslavje'],
                ['mk' => 'Вргорац', 'sr' => 'Вргорац', 'hr' => 'Vrgorac', 'sq' => 'Vrgorac', 'en' => 'Vrgorac'],
                ['mk' => 'Биоград на Мору', 'sr' => 'Биоград на Мору', 'hr' => 'Biograd na Moru', 'sq' => 'Biograd na Moru', 'en' => 'Biograd na Moru'],
                ['mk' => 'Златар', 'sr' => 'Златар', 'hr' => 'Zlatar', 'sq' => 'Zlatar', 'en' => 'Zlatar'],
                ['mk' => 'Вараждинске Топлице', 'sr' => 'Вараждинске Топлице', 'hr' => 'Varaždinske Toplice', 'sq' => 'Varaždinske Toplice', 'en' => 'Varaždinske Toplice'],
                ['mk' => 'Корчула', 'sr' => 'Корчула', 'hr' => 'Korčula', 'sq' => 'Korčula', 'en' => 'Korčula'],
                ['mk' => 'Грубишно Поље', 'sr' => 'Грубишно Поље', 'hr' => 'Grubišno Polje', 'sq' => 'Grubišno Polje', 'en' => 'Grubišno Polje'],
                ['mk' => 'Доња Стубица', 'sr' => 'Доња Стубица', 'hr' => 'Donja Stubica', 'sq' => 'Donja Stubica', 'en' => 'Donja Stubica'],
                ['mk' => 'Делнице', 'sr' => 'Делнице', 'hr' => 'Delnice', 'sq' => 'Delnice', 'en' => 'Delnice'],
                ['mk' => 'Липик', 'sr' => 'Липик', 'hr' => 'Lipik', 'sq' => 'Lipik', 'en' => 'Lipik'],
                ['mk' => 'Илок', 'sr' => 'Илок', 'hr' => 'Ilok', 'sq' => 'Ilok', 'en' => 'Ilok'],
                ['mk' => 'Оток', 'sr' => 'Оток', 'hr' => 'Otok', 'sq' => 'Otok', 'en' => 'Otok'],
                ['mk' => 'Кутјево', 'sr' => 'Кутјево', 'hr' => 'Kutjevo', 'sq' => 'Kutjevo', 'en' => 'Kutjevo'],
                ['mk' => 'Ораховица', 'sr' => 'Ораховица', 'hr' => 'Orahovica', 'sq' => 'Orahovica', 'en' => 'Orahovica'],
                ['mk' => 'Бује', 'sr' => 'Бује', 'hr' => 'Buje', 'sq' => 'Buje', 'en' => 'Buje'],
                ['mk' => 'Нови Винодолски', 'sr' => 'Нови Винодолски', 'hr' => 'Novi Vinodolski', 'sq' => 'Novi Vinodolski', 'en' => 'Novi Vinodolski'],
                ['mk' => 'Супетар', 'sr' => 'Супетар', 'hr' => 'Supetar', 'sq' => 'Supetar', 'en' => 'Supetar'],
                ['mk' => 'Слуњ', 'sr' => 'Слуњ', 'hr' => 'Slunj', 'sq' => 'Slunj', 'en' => 'Slunj'],
                ['mk' => 'Краљевица', 'sr' => 'Краљевица', 'hr' => 'Kraljevica', 'sq' => 'Kraljevica', 'en' => 'Kraljevica'],
                ['mk' => 'Хвар', 'sr' => 'Хвар', 'hr' => 'Hvar', 'sq' => 'Hvar', 'en' => 'Hvar'],
                ['mk' => 'Новиград', 'sr' => 'Новиград', 'hr' => 'Novigrad', 'sq' => 'Novigrad', 'en' => 'Novigrad'],
                ['mk' => 'Врбовско', 'sr' => 'Врбовско', 'hr' => 'Vrbovsko', 'sq' => 'Vrbovsko', 'en' => 'Vrbovsko'],
                ['mk' => 'Новаља', 'sr' => 'Новаља', 'hr' => 'Novalja', 'sq' => 'Novalja', 'en' => 'Novalja'],
                ['mk' => 'Обровац', 'sr' => 'Обровац', 'hr' => 'Obrovac', 'sq' => 'Obrovac', 'en' => 'Obrovac'],
                ['mk' => 'Скрадин', 'sr' => 'Скрадин', 'hr' => 'Skradin', 'sq' => 'Skradin', 'en' => 'Skradin'],
                ['mk' => 'Чабар', 'sr' => 'Чабар', 'hr' => 'Čabar', 'sq' => 'Čabar', 'en' => 'Čabar'],
                ['mk' => 'Паг', 'sr' => 'Паг', 'hr' => 'Pag', 'sq' => 'Pag', 'en' => 'Pag'],
                ['mk' => 'Опузен', 'sr' => 'Опузен', 'hr' => 'Opuzen', 'sq' => 'Opuzen', 'en' => 'Opuzen'],
                ['mk' => 'Стари Град', 'sr' => 'Стари Град', 'hr' => 'Stari Grad', 'sq' => 'Stari Grad', 'en' => 'Stari Grad'],
                ['mk' => 'Црес', 'sr' => 'Црес', 'hr' => 'Cres', 'sq' => 'Cres', 'en' => 'Cres'],
                ['mk' => 'Нин', 'sr' => 'Нин', 'hr' => 'Nin', 'sq' => 'Nin', 'en' => 'Nin'],
                ['mk' => 'Клањец', 'sr' => 'Клањец', 'hr' => 'Klanjec', 'sq' => 'Klanjec', 'en' => 'Klanjec'],
                ['mk' => 'Вис', 'sr' => 'Вис', 'hr' => 'Vis', 'sq' => 'Vis', 'en' => 'Vis'],
                ['mk' => 'Хрватска Костајница', 'sr' => 'Хрватска Костајница', 'hr' => 'Hrvatska Kostajnica', 'sq' => 'Hrvatska Kostajnica', 'en' => 'Hrvatska Kostajnica'],
                ['mk' => 'Врлика', 'sr' => 'Врлика', 'hr' => 'Vrlika', 'sq' => 'Vrlika', 'en' => 'Vrlika'],
                ['mk' => 'Комижа', 'sr' => 'Комижа', 'hr' => 'Komiža', 'sq' => 'Komiža', 'en' => 'Komiža'],
            ],
            'AL' => [
                ['mk' => 'Тирана', 'sr' => 'Тирана', 'hr' => 'Tirana', 'sq' => 'Tiranë', 'en' => 'Tirana'],
                ['mk' => 'Дурес', 'sr' => 'Драч', 'hr' => 'Drač', 'sq' => 'Durrës', 'en' => 'Durrës'],
                ['mk' => 'Влора', 'sr' => 'Валона', 'hr' => 'Valona', 'sq' => 'Vlorë', 'en' => 'Vlorë'],
                ['mk' => 'Скадар', 'sr' => 'Скадар', 'hr' => 'Skadar', 'sq' => 'Shkodër', 'en' => 'Shkodër'],
                ['mk' => 'Елбасан', 'sr' => 'Елбасан', 'hr' => 'Elbasan', 'sq' => 'Elbasan', 'en' => 'Elbasan'],
                ['mk' => 'Корча', 'sr' => 'Корча', 'hr' => 'Korča', 'sq' => 'Korçë', 'en' => 'Korçë'],
                ['mk' => 'Бајрам Цурри', 'sr' => 'Бајрам Цурри', 'hr' => 'Bajram Curri', 'sq' => 'Bajram Curri', 'en' => 'Bajram Curri'],
                ['mk' => 'Бајзë', 'sr' => 'Бајзë', 'hr' => 'Bajzë', 'sq' => 'Bajzë', 'en' => 'Bajzë'],
                ['mk' => 'Баллсх', 'sr' => 'Баллсх', 'hr' => 'Ballsh', 'sq' => 'Ballsh', 'en' => 'Ballsh'],
                ['mk' => 'Берат', 'sr' => 'Берат', 'hr' => 'Berat', 'sq' => 'Berat', 'en' => 'Berat'],
                ['mk' => 'Билисхт', 'sr' => 'Билисхт', 'hr' => 'Bilisht', 'sq' => 'Bilisht', 'en' => 'Bilisht'],
                ['mk' => 'Булqизë', 'sr' => 'Булqизë', 'hr' => 'Bulqizë', 'sq' => 'Bulqizë', 'en' => 'Bulqizë'],
                ['mk' => 'Буррел', 'sr' => 'Буррел', 'hr' => 'Burrel', 'sq' => 'Burrel', 'en' => 'Burrel'],
                ['mk' => 'Цëррик', 'sr' => 'Цëррик', 'hr' => 'Cërrik', 'sq' => 'Cërrik', 'en' => 'Cërrik'],
                ['mk' => 'Çороводë', 'sr' => 'Çороводë', 'hr' => 'Çorovodë', 'sq' => 'Çorovodë', 'en' => 'Çorovodë'],
                ['mk' => 'Делвинë', 'sr' => 'Делвинë', 'hr' => 'Delvinë', 'sq' => 'Delvinë', 'en' => 'Delvinë'],
                ['mk' => 'Дивјакë', 'sr' => 'Дивјакë', 'hr' => 'Divjakë', 'sq' => 'Divjakë', 'en' => 'Divjakë'],
                ['mk' => 'Ерсекë', 'sr' => 'Ерсекë', 'hr' => 'Ersekë', 'sq' => 'Ersekë', 'en' => 'Ersekë'],
                ['mk' => 'Фиер', 'sr' => 'Фиер', 'hr' => 'Fier', 'sq' => 'Fier', 'en' => 'Fier'],
                ['mk' => 'Фиерзë', 'sr' => 'Фиерзë', 'hr' => 'Fierzë', 'sq' => 'Fierzë', 'en' => 'Fierzë'],
                ['mk' => 'Финиq', 'sr' => 'Финиq', 'hr' => 'Finiq', 'sq' => 'Finiq', 'en' => 'Finiq'],
                ['mk' => 'Фусхë-Аррëз', 'sr' => 'Фусхë-Аррëз', 'hr' => 'Fushë-Arrëz', 'sq' => 'Fushë-Arrëz', 'en' => 'Fushë-Arrëz'],
                ['mk' => 'Фусхë-Крујë', 'sr' => 'Фусхë-Крујë', 'hr' => 'Fushë-Krujë', 'sq' => 'Fushë-Krujë', 'en' => 'Fushë-Krujë'],
                ['mk' => 'Гјирокастëр', 'sr' => 'Гјирокастëр', 'hr' => 'Gjirokastër', 'sq' => 'Gjirokastër', 'en' => 'Gjirokastër'],
                ['mk' => 'Грамсх', 'sr' => 'Грамсх', 'hr' => 'Gramsh', 'sq' => 'Gramsh', 'en' => 'Gramsh'],
                ['mk' => 'Химарë', 'sr' => 'Химарë', 'hr' => 'Himarë', 'sq' => 'Himarë', 'en' => 'Himarë'],
                ['mk' => 'Камëз', 'sr' => 'Камëз', 'hr' => 'Kamëz', 'sq' => 'Kamëz', 'en' => 'Kamëz'],
                ['mk' => 'Кавајë', 'sr' => 'Кавајë', 'hr' => 'Kavajë', 'sq' => 'Kavajë', 'en' => 'Kavajë'],
                ['mk' => 'Кëлцyрë', 'sr' => 'Кëлцyрë', 'hr' => 'Këlcyrë', 'sq' => 'Këlcyrë', 'en' => 'Këlcyrë'],
                ['mk' => 'Клос', 'sr' => 'Клос', 'hr' => 'Klos', 'sq' => 'Klos', 'en' => 'Klos'],
                ['mk' => 'Кониспол', 'sr' => 'Кониспол', 'hr' => 'Konispol', 'sq' => 'Konispol', 'en' => 'Konispol'],
                ['mk' => 'Коплик', 'sr' => 'Коплик', 'hr' => 'Koplik', 'sq' => 'Koplik', 'en' => 'Koplik'],
                ['mk' => 'Крастë', 'sr' => 'Крастë', 'hr' => 'Krastë', 'sq' => 'Krastë', 'en' => 'Krastë'],
                ['mk' => 'Кррабë', 'sr' => 'Кррабë', 'hr' => 'Krrabë', 'sq' => 'Krrabë', 'en' => 'Krrabë'],
                ['mk' => 'Крујë', 'sr' => 'Крујë', 'hr' => 'Krujë', 'sq' => 'Krujë', 'en' => 'Krujë'],
                ['mk' => 'Крумë', 'sr' => 'Крумë', 'hr' => 'Krumë', 'sq' => 'Krumë', 'en' => 'Krumë'],
                ['mk' => 'Куçовë', 'sr' => 'Куçовë', 'hr' => 'Kuçovë', 'sq' => 'Kuçovë', 'en' => 'Kuçovë'],
                ['mk' => 'Кукëс', 'sr' => 'Кукëс', 'hr' => 'Kukës', 'sq' => 'Kukës', 'en' => 'Kukës'],
                ['mk' => 'Курбнесх', 'sr' => 'Курбнесх', 'hr' => 'Kurbnesh', 'sq' => 'Kurbnesh', 'en' => 'Kurbnesh'],
                ['mk' => 'Лаç', 'sr' => 'Лаç', 'hr' => 'Laç', 'sq' => 'Laç', 'en' => 'Laç'],
                ['mk' => 'Лесковик', 'sr' => 'Лесковик', 'hr' => 'Leskovik', 'sq' => 'Leskovik', 'en' => 'Leskovik'],
                ['mk' => 'Лезхë', 'sr' => 'Лезхë', 'hr' => 'Lezhë', 'sq' => 'Lezhë', 'en' => 'Lezhë'],
                ['mk' => 'Либоховë', 'sr' => 'Либоховë', 'hr' => 'Libohovë', 'sq' => 'Libohovë', 'en' => 'Libohovë'],
                ['mk' => 'Либразхд', 'sr' => 'Либразхд', 'hr' => 'Librazhd', 'sq' => 'Librazhd', 'en' => 'Librazhd'],
                ['mk' => 'Лусхњë', 'sr' => 'Лусхњë', 'hr' => 'Lushnjë', 'sq' => 'Lushnjë', 'en' => 'Lushnjë'],
                ['mk' => 'Малиq', 'sr' => 'Малиq', 'hr' => 'Maliq', 'sq' => 'Maliq', 'en' => 'Maliq'],
                ['mk' => 'Мамуррас', 'sr' => 'Мамуррас', 'hr' => 'Mamurras', 'sq' => 'Mamurras', 'en' => 'Mamurras'],
                ['mk' => 'Манëз', 'sr' => 'Манëз', 'hr' => 'Manëz', 'sq' => 'Manëz', 'en' => 'Manëz'],
                ['mk' => 'Мемалиај', 'sr' => 'Мемалиај', 'hr' => 'Memaliaj', 'sq' => 'Memaliaj', 'en' => 'Memaliaj'],
                ['mk' => 'Милот', 'sr' => 'Милот', 'hr' => 'Milot', 'sq' => 'Milot', 'en' => 'Milot'],
                ['mk' => 'Орикум', 'sr' => 'Орикум', 'hr' => 'Orikum', 'sq' => 'Orikum', 'en' => 'Orikum'],
                ['mk' => 'Патос', 'sr' => 'Патос', 'hr' => 'Patos', 'sq' => 'Patos', 'en' => 'Patos'],
                ['mk' => 'Пеqин', 'sr' => 'Пеqин', 'hr' => 'Peqin', 'sq' => 'Peqin', 'en' => 'Peqin'],
                ['mk' => 'Пëрмет', 'sr' => 'Пëрмет', 'hr' => 'Përmet', 'sq' => 'Përmet', 'en' => 'Përmet'],
                ['mk' => 'Песхкопи', 'sr' => 'Песхкопи', 'hr' => 'Peshkopi', 'sq' => 'Peshkopi', 'en' => 'Peshkopi'],
                ['mk' => 'Поградец', 'sr' => 'Поградец', 'hr' => 'Pogradec', 'sq' => 'Pogradec', 'en' => 'Pogradec'],
                ['mk' => 'Полиçан', 'sr' => 'Полиçан', 'hr' => 'Poliçan', 'sq' => 'Poliçan', 'en' => 'Poliçan'],
                ['mk' => 'Пррењас', 'sr' => 'Пррењас', 'hr' => 'Prrenjas', 'sq' => 'Prrenjas', 'en' => 'Prrenjas'],
                ['mk' => 'Пукë', 'sr' => 'Пукë', 'hr' => 'Pukë', 'sq' => 'Pukë', 'en' => 'Pukë'],
                ['mk' => 'Репс', 'sr' => 'Репс', 'hr' => 'Reps', 'sq' => 'Reps', 'en' => 'Reps'],
                ['mk' => 'Росковец', 'sr' => 'Росковец', 'hr' => 'Roskovec', 'sq' => 'Roskovec', 'en' => 'Roskovec'],
                ['mk' => 'Ррëсхен', 'sr' => 'Ррëсхен', 'hr' => 'Rrëshen', 'sq' => 'Rrëshen', 'en' => 'Rrëshen'],
                ['mk' => 'Ррогозхинë', 'sr' => 'Ррогозхинë', 'hr' => 'Rrogozhinë', 'sq' => 'Rrogozhinë', 'en' => 'Rrogozhinë'],
                ['mk' => 'Рубик', 'sr' => 'Рубик', 'hr' => 'Rubik', 'sq' => 'Rubik', 'en' => 'Rubik'],
                ['mk' => 'Сарандë', 'sr' => 'Сарандë', 'hr' => 'Sarandë', 'sq' => 'Sarandë', 'en' => 'Sarandë'],
                ['mk' => 'Селеницë', 'sr' => 'Селеницë', 'hr' => 'Selenicë', 'sq' => 'Selenicë', 'en' => 'Selenicë'],
                ['mk' => 'Схëнгјин', 'sr' => 'Схëнгјин', 'hr' => 'Shëngjin', 'sq' => 'Shëngjin', 'en' => 'Shëngjin'],
                ['mk' => 'Схијак', 'sr' => 'Схијак', 'hr' => 'Shijak', 'sq' => 'Shijak', 'en' => 'Shijak'],
                ['mk' => 'Суктх', 'sr' => 'Суктх', 'hr' => 'Sukth', 'sq' => 'Sukth', 'en' => 'Sukth'],
                ['mk' => 'Тепеленë', 'sr' => 'Тепеленë', 'hr' => 'Tepelenë', 'sq' => 'Tepelenë', 'en' => 'Tepelenë'],
                ['mk' => 'Улëз', 'sr' => 'Улëз', 'hr' => 'Ulëz', 'sq' => 'Ulëz', 'en' => 'Ulëz'],
                ['mk' => 'Ура Вајгуроре', 'sr' => 'Ура Вајгуроре', 'hr' => 'Ura Vajgurore', 'sq' => 'Ura Vajgurore', 'en' => 'Ura Vajgurore'],
                ['mk' => 'Вау и Дејëс', 'sr' => 'Вау и Дејëс', 'hr' => 'Vau i Dejës', 'sq' => 'Vau i Dejës', 'en' => 'Vau i Dejës'],
                ['mk' => 'Ворë', 'sr' => 'Ворë', 'hr' => 'Vorë', 'sq' => 'Vorë', 'en' => 'Vorë'],
            ],
            'XK' => [
                ['mk' => 'Приштина', 'sr' => 'Приштина', 'hr' => 'Priština', 'sq' => 'Prishtina', 'en' => 'Priština'],
                ['mk' => 'Призрен', 'sr' => 'Призрен', 'hr' => 'Prizren', 'sq' => 'Prizreni', 'en' => 'Prizren'],
                ['mk' => 'Пеќ', 'sr' => 'Пећ', 'hr' => 'Peć', 'sq' => 'Peja', 'en' => 'Peć'],
                ['mk' => 'Ѓаковица', 'sr' => 'Ђаковица', 'hr' => 'Đakovica', 'sq' => 'Gjakova', 'en' => 'Đakovica'],
                ['mk' => 'Урошевац', 'sr' => 'Урошевац', 'hr' => 'Uroševac', 'sq' => 'Ferizaj', 'en' => 'Uroševac'],
                ['mk' => 'Митровица', 'sr' => 'Митровица', 'hr' => 'Mitrovica', 'sq' => 'Mitrovica', 'en' => 'Mitrovica'],
                ['mk' => 'Дечани', 'sr' => 'Дечани', 'hr' => 'Dečani', 'sq' => 'Deçan', 'en' => 'Dečani'],
                ['mk' => 'Драгаш', 'sr' => 'Драгаш', 'hr' => 'Dragaš', 'sq' => 'Dragash', 'en' => 'Dragaš'],
                ['mk' => 'Глоговац', 'sr' => 'Глоговац', 'hr' => 'Glogovac', 'sq' => 'Drenas', 'en' => 'Glogovac'],
                ['mk' => 'Косово Поље', 'sr' => 'Косово Поље', 'hr' => 'Kosovo Polje', 'sq' => 'Fushë Kosova', 'en' => 'Kosovo Polje'],
                ['mk' => 'Гњилане', 'sr' => 'Гњилане', 'hr' => 'Gnjilane', 'sq' => 'Gjilan', 'en' => 'Gnjilane'],
                ['mk' => 'Исток', 'sr' => 'Исток', 'hr' => 'Istok', 'sq' => 'Istog', 'en' => 'Istok'],
                ['mk' => 'Качаник', 'sr' => 'Качаник', 'hr' => 'Kačanik', 'sq' => 'Kaçanik', 'en' => 'Kačanik'],
                ['mk' => 'Косовска Каменица', 'sr' => 'Косовска Каменица', 'hr' => 'Kosovska Kamenica', 'sq' => 'Kamenicë', 'en' => 'Kosovska Kamenica'],
                ['mk' => 'Клина', 'sr' => 'Клина', 'hr' => 'Klina', 'sq' => 'Klinë', 'en' => 'Klina'],
                ['mk' => 'Липљан', 'sr' => 'Липљан', 'hr' => 'Lipljan', 'sq' => 'Lipjan', 'en' => 'Lipljan'],
                ['mk' => 'Малишево', 'sr' => 'Малишево', 'hr' => 'Mališevo', 'sq' => 'Malishevë', 'en' => 'Mališevo'],
                ['mk' => 'Обилиќ', 'sr' => 'Обилић', 'hr' => 'Obilić', 'sq' => 'Obiliq', 'en' => 'Obilić'],
                ['mk' => 'Подујево', 'sr' => 'Подујево', 'hr' => 'Podujevo', 'sq' => 'Podujevë', 'en' => 'Podujevo'],
                ['mk' => 'Ораховац', 'sr' => 'Ораховац', 'hr' => 'Orahovac', 'sq' => 'Rahovec', 'en' => 'Orahovac'],
                ['mk' => 'Србица', 'sr' => 'Србица', 'hr' => 'Srbica', 'sq' => 'Skenderaj', 'en' => 'Srbica'],
                ['mk' => 'Сува Река', 'sr' => 'Сува Река', 'hr' => 'Suva Reka', 'sq' => 'Suharekë', 'en' => 'Suva Reka'],
                ['mk' => 'Штрпце', 'sr' => 'Штрпце', 'hr' => 'Štrpce', 'sq' => 'Shtërpcë', 'en' => 'Štrpce'],
                ['mk' => 'Штимље', 'sr' => 'Штимље', 'hr' => 'Štimlje', 'sq' => 'Shtime', 'en' => 'Štimlje'],
                ['mk' => 'Витина', 'sr' => 'Витина', 'hr' => 'Vitina', 'sq' => 'Viti', 'en' => 'Vitina'],
                ['mk' => 'Вучитрн', 'sr' => 'Вучитрн', 'hr' => 'Vučitrn', 'sq' => 'Vushtrri', 'en' => 'Vučitrn'],
                ['mk' => 'Зубин Поток', 'sr' => 'Зубин Поток', 'hr' => 'Zubin Potok', 'sq' => 'Zubin Potok', 'en' => 'Zubin Potok'],
                ['mk' => 'Звечан', 'sr' => 'Звечан', 'hr' => 'Zvečan', 'sq' => 'Zveçan', 'en' => 'Zvečan'],
                ['mk' => 'Лепосавиќ', 'sr' => 'Лепосавић', 'hr' => 'Leposavić', 'sq' => 'Leposaviq', 'en' => 'Leposavić'],
                ['mk' => 'Грачаница', 'sr' => 'Грачаница', 'hr' => 'Gračanica', 'sq' => 'Graçanicë', 'en' => 'Gračanica'],
                ['mk' => 'Ново Брдо', 'sr' => 'Ново Брдо', 'hr' => 'Novo Brdo', 'sq' => 'Novobërdë', 'en' => 'Novo Brdo'],
                ['mk' => 'Ранилуг', 'sr' => 'Ранилуг', 'hr' => 'Ranilug', 'sq' => 'Ranillug', 'en' => 'Ranilug'],
                ['mk' => 'Партеш', 'sr' => 'Партеш', 'hr' => 'Parteš', 'sq' => 'Partesh', 'en' => 'Parteš'],
                ['mk' => 'Клокот', 'sr' => 'Клокот', 'hr' => 'Klokot', 'sq' => 'Kllokot', 'en' => 'Klokot'],
                ['mk' => 'Мамуша', 'sr' => 'Мамуша', 'hr' => 'Mamuša', 'sq' => 'Mamushë', 'en' => 'Mamuša'],
                ['mk' => 'Хан и Елезит', 'sr' => 'Хан и Елезит', 'hr' => 'Han i Elezit', 'sq' => 'Elez Han', 'en' => 'Han i Elezit'],
                ['mk' => 'Јуник', 'sr' => 'Јуник', 'hr' => 'Junik', 'sq' => 'Junik', 'en' => 'Junik'],
            ],
            'BG' => [
                ['mk' => 'Софија', 'sr' => 'Софија', 'hr' => 'Sofija', 'sq' => 'Sofja', 'bg' => 'София', 'el' => 'Σόφια', 'en' => 'Sofia'],
                ['mk' => 'Пловдив', 'sr' => 'Пловдив', 'hr' => 'Plovdiv', 'sq' => 'Plovdiv', 'bg' => 'Пловдив', 'el' => 'Φιλιππούπολη', 'en' => 'Plovdiv'],
                ['mk' => 'Варна', 'sr' => 'Варна', 'hr' => 'Varna', 'sq' => 'Varna', 'bg' => 'Варна', 'el' => 'Βάρνα', 'en' => 'Varna'],
                ['mk' => 'Бургас', 'sr' => 'Бургас', 'hr' => 'Burgas', 'sq' => 'Burgas', 'bg' => 'Бургас', 'el' => 'Μπουργκάς', 'en' => 'Burgas'],
                ['mk' => 'Русе', 'sr' => 'Русе', 'hr' => 'Ruse', 'sq' => 'Ruse', 'bg' => 'Русе', 'el' => 'Ρούσε', 'en' => 'Ruse'],
                ['mk' => 'Стара Загора', 'sr' => 'Стара Загора', 'hr' => 'Stara Zagora', 'sq' => 'Stara Zagora', 'bg' => 'Стара Загора', 'el' => 'Στάρα Ζαγόρα', 'en' => 'Stara Zagora'],
                ['mk' => 'Плевен', 'sr' => 'Плевен', 'hr' => 'Pleven', 'sq' => 'Pleven', 'bg' => 'Плевен', 'el' => 'Πλέβεν', 'en' => 'Pleven'],
                ['mk' => 'Сливен', 'sr' => 'Сливен', 'hr' => 'Sliven', 'sq' => 'Sliven', 'bg' => 'Сливен', 'el' => 'Σλίβεν', 'en' => 'Sliven'],
                ['mk' => 'Добрич', 'sr' => 'Добрич', 'hr' => 'Dobrič', 'sq' => 'Dobriç', 'bg' => 'Добрич', 'el' => 'Ντόμπριτς', 'en' => 'Dobrič'],
                ['mk' => 'Шумен', 'sr' => 'Шумен', 'hr' => 'Šumen', 'sq' => 'Shumen', 'bg' => 'Шумен', 'el' => 'Σούμεν', 'en' => 'Šumen'],
                ['mk' => 'Перник', 'sr' => 'Перник', 'hr' => 'Pernik', 'sq' => 'Pernik', 'bg' => 'Перник', 'el' => 'Πέρνικ', 'en' => 'Pernik'],
                ['mk' => 'Хасково', 'sr' => 'Хасково', 'hr' => 'Haskovo', 'sq' => 'Haskovo', 'bg' => 'Хасково', 'el' => 'Χάσκοβο', 'en' => 'Haskovo'],
                ['mk' => 'Јамбол', 'sr' => 'Јамбол', 'hr' => 'Jambol', 'sq' => 'Jamboll', 'bg' => 'Ямбол', 'el' => 'Γιάμπολ', 'en' => 'Jambol'],
                ['mk' => 'Пазарџик', 'sr' => 'Пазарџик', 'hr' => 'Pazardžik', 'sq' => 'Pazarxhik', 'bg' => 'Пазарджик', 'el' => 'Παζάρτζικ', 'en' => 'Pazardžik'],
                ['mk' => 'Благоевград', 'sr' => 'Благоевград', 'hr' => 'Blagoevgrad', 'sq' => 'Blagoevgrad', 'bg' => 'Благоевград', 'el' => 'Μπλαγκόεβγκραντ', 'en' => 'Blagoevgrad'],
            ],
            'GR' => [
                ['mk' => 'Атина', 'sr' => 'Атина', 'hr' => 'Atena', 'sq' => 'Athina', 'bg' => 'Атина', 'el' => 'Αθήνα', 'en' => 'Athens'],
                ['mk' => 'Солун', 'sr' => 'Солун', 'hr' => 'Solun', 'sq' => 'Selanik', 'bg' => 'Солун', 'el' => 'Θεσσαλονίκη', 'en' => 'Thessaloniki'],
                ['mk' => 'Патра', 'sr' => 'Патра', 'hr' => 'Patras', 'sq' => 'Patra', 'bg' => 'Патра', 'el' => 'Πάτρα', 'en' => 'Patras'],
                ['mk' => 'Ираклион', 'sr' => 'Ираклион', 'hr' => 'Iraklion', 'sq' => 'Irakli', 'bg' => 'Ираклион', 'el' => 'Ηράκλειο', 'en' => 'Iraklion'],
                ['mk' => 'Лариса', 'sr' => 'Лариса', 'hr' => 'Larisa', 'sq' => 'Larisa', 'bg' => 'Лариса', 'el' => 'Λάρισα', 'en' => 'Larisa'],
                ['mk' => 'Волос', 'sr' => 'Волос', 'hr' => 'Volos', 'sq' => 'Volos', 'bg' => 'Волос', 'el' => 'Βόλος', 'en' => 'Volos'],
                ['mk' => 'Јанина', 'sr' => 'Јањина', 'hr' => 'Janjina', 'sq' => 'Janinë', 'bg' => 'Янина', 'el' => 'Ιωάννινα', 'en' => 'Ioannina'],
                ['mk' => 'Ханија', 'sr' => 'Канија', 'hr' => 'Hanja', 'sq' => 'Kanea', 'bg' => 'Ханя', 'el' => 'Χανιά', 'en' => 'Chania'],
                ['mk' => 'Кавала', 'sr' => 'Кавала', 'hr' => 'Kavala', 'sq' => 'Kavala', 'bg' => 'Кавала', 'el' => 'Καβάλα', 'en' => 'Kavala'],
                ['mk' => 'Сер', 'sr' => 'Сер', 'hr' => 'Ser', 'sq' => 'Serre', 'bg' => 'Сяр', 'el' => 'Σέρρες', 'en' => 'Serres'],
                ['mk' => 'Александрополис', 'sr' => 'Александрополис', 'hr' => 'Aleksandrupoli', 'sq' => 'Aleksandropoli', 'bg' => 'Александруполис', 'el' => 'Αλεξανδρούπολη', 'en' => 'Alexandroupoli'],
                ['mk' => 'Ксанти', 'sr' => 'Ксанти', 'hr' => 'Ksanti', 'sq' => 'Ksanthi', 'bg' => 'Ксанти', 'el' => 'Ξάνθη', 'en' => 'Ksanti'],
                ['mk' => 'Гумурџина', 'sr' => 'Комотини', 'hr' => 'Komotini', 'sq' => 'Gumulxhinë', 'bg' => 'Гюмюрджина', 'el' => 'Κομοτηνή', 'en' => 'Komotini'],
                ['mk' => 'Катерини', 'sr' => 'Катерини', 'hr' => 'Katerini', 'sq' => 'Katerini', 'bg' => 'Катерини', 'el' => 'Κατερίνη', 'en' => 'Katerini'],
                ['mk' => 'Родос', 'sr' => 'Родос', 'hr' => 'Rodos', 'sq' => 'Rodos', 'bg' => 'Родос', 'el' => 'Ρόδος', 'en' => 'Rhodes'],
            ],
        ];

        foreach ($cities as $countryCode => $cityList) {
            $country = Country::where('code', $countryCode)->firstOrFail();

            foreach ($cityList as $name) {
                $city = City::where('country_id', $country->id)
                    ->where('name->mk', $name['mk'])
                    ->first() ?? new City(['country_id' => $country->id]);

                // Merge rather than overwrite so re-running the seeder after adding a
                // new locale (e.g. 'en') backfills existing rows instead of skipping them.
                foreach ($name as $locale => $value) {
                    $city->setTranslation('name', $locale, $value);
                }

                $city->save();
            }
        }
    }
}
